# Generated by Django 4.2.2 on 2023-07-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_rawhtml', '0002_auto_20221216_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawhtmlplugindata',
            name='cmsplugin_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='%(app_label)s_%(class)s',
                serialize=False,
                to='cms.cmsplugin'
            ),
        ),
    ]
